image:
  repository: lgvanalytics.azurecr.io/noiseprocesses
  tag: "4.0.5-1.0.9"
  pullPolicy: IfNotPresent
  pullSecrets: []    # e.g. - name: regcred

nameOverride: ""
fullnameOverride: ""

replicaCount:
  api: 1
  worker: 1

podLabels:
  api: {}    # e.g. environment: prod
  worker: {} # e.g. type: background

# node selector
nodeSelector:
  worker:
    ump.reservedFor: apps
  api:
    ump.reservedFor: apps
# Node tolerations
tolerations:
  api:     
    - key: "ump/reservedFor"
      operator: "Equal"
      value: "apps"
      effect: "NoSchedule"
    - key: "ump/reservedFor"
      operator: "Equal"
      value: "apps"
      effect: "NoExecute"
  worker:
    - key: "ump/reservedFor"
      operator: "Equal"
      value: "apps"
      effect: "NoSchedule"
    - key: "ump/reservedFor"
      operator: "Equal"
      value: "apps"
      effect: "NoExecute"

service:
  type: ClusterIP
  port: 8008

config:
  apiTitle: "Noise calculation - OGC API Processes"
  apiDescription: "An OGC API Processes implementation for noise calculations."
  
  resultCache:
    host: "redis"
    port: 6379
    db: 1
    existingSecret: ""
    existingSecretKey: ""
    resultsTempTtlHours: 24
#
  celery:
    brokerHost: "redis"
    brokerPort: 6379
    brokerDb: 0
    resultsTtlDays: 7
    taskTlimitHard: 1800 # seconds
    taskTlimitSoft: 1500 # seconds
    jobStatusTtlDays: 7
    existingSecret: ""
    existingSecretKey: ""
#
  syncExecutionTimeoutSeconds: 10
#
  logLevel: "DEBUG"
  javaLibDir: ""
  javaMaxHeapSize: "4096m"
  javaInitialHeapSize: "1024m"

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  api:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  worker:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 2
      memory: 3Gi

autoscaling:
  api:
    hpa:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilization: 70
      targetMemoryUtilization: 80
  worker:
    hpa:
      enabled: false
      minReplicas: 2
      maxReplicas: 15
      targetCPUUtilization: 60
      targetMemoryUtilization: 75
    vpa:
      enabled: false  # Make VPA optional
      minAllowedCPU: "200m"
      minAllowedMemory: "256Mi"
      maxAllowedCPU: "4"
      maxAllowedMemory: "8Gi"
    keda:
      enabled: true
      minReplicas: 0 # scale down to zero to spare resources
      maxReplicas: 5
      queueName: "celery"
      triggerType: "redis"
      triggers:
        - type: redis
          metadata:
            address: "redis:6379"
            listName: "celery"
            listLength: "3" # Scale up if more than 3 tasks in queue
            db: "0"