[tool.bumpversion]
current_version = "1.1.1+4.0.5"
commit = true
tag = true
message = "Bump version: {current_version} → {new_version}"

serialize = [
    "{project_major}.{project_minor}.{project_patch}+{major}.{minor}.{patch}",
]

parse = """
(?P<project_major>0|[1-9]\\d*)\\.
(?P<project_minor>0|[1-9]\\d*)\\.
(?P<project_patch>0|[1-9]\\d*)
+
(?P<major>0|[1-9]\\d*)\\.
(?P<minor>0|[1-9]\\d*)\\.
(?P<patch>0|[1-9]\\d*)
"""

# Define the parts of the version
[tool.bumpversion.parts.major]
[tool.bumpversion.parts.minor]
[tool.bumpversion.parts.patch]

[tool.bumpversion.parts.project_major]
bumpable = true

[tool.bumpversion.parts.project_minor]
bumpable = true

[tool.bumpversion.parts.project_patch]
bumpable = true

# File-specific configurations
[[tool.bumpversion.file]]
filename = "Dockerfile"
search = 'com.lgv.uda.version="{current_version}"'
replace = 'com.lgv.uda.version="{new_version}"'

[[tool.bumpversion.file]]
filename = ".env"
search = "IMAGE_TAG={current_version}"
replace = "IMAGE_TAG={new_version}"

[[tool.bumpversion.file]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'