networks:
  dev:
    name: ${DOCKER_DEV_NETWORK}
    external: true
volumes:
  redis_data:
    driver: local

services:
  api:
    image: ${CONTAINER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    restart: "no"
    environment:
      RESULT_CACHE_HOST: "redis"
      RESULT_CACHE_PORT: 6379
      RESULT_CACHE_DB: 1

      CELERY_BROKER_HOST: "redis"
      CELERY_BROKER_PORT: 6379
      CELERY_BROKER_DB: 0
    ports:
      - 8000:8000
    command: ['uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '8000']
    networks:
      - dev

  worker:
    image: ${CONTAINER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    restart: "no"
    environment:
      RESULT_CACHE_HOST: "redis"
      RESULT_CACHE_PORT: 6379
      RESULT_CACHE_DB: 1

      CELERY_BROKER_HOST: "redis"
      CELERY_BROKER_PORT: 6379
      CELERY_BROKER_DB: 0
    # ports:
    #   - ${WEBAPP_PORT_CONTAINER}:${WEBAPP_PORT}
    command: ['celery', '-A', 'fastprocesses.worker.celery_app', 'worker', '--loglevel=debug']
    networks:
      - dev

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.27.1
    expose: 
      - ${REDIS_PORT}
    restart: "unless-stopped"
    command: dragonfly --requirepass "" # --appendonly yes
    networks:
      - dev
    volumes:
      - redis_data:/data