apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "noise-modelling-api.fullname" . }}
  labels:
    {{- include "noise-modelling-api.labels" . | nindent 4 }}
data:
  FP_API_TITLE: "{{ .Values.config.apiTitle }}"
  FP_API_DESCRIPTION: "{{ .Values.config.apiDescription }}"
  FP_RESULT_CACHE_HOST: "{{ .Values.config.resultCache.host }}"
  FP_RESULT_CACHE_PORT: "{{ .Values.config.resultCache.port }}"
  FP_RESULT_CACHE_DB: "{{ .Values.config.resultCache.db }}"
  FP_CELERY_BROKER_HOST: "{{ .Values.config.celery.brokerHost }}"
  FP_CELERY_BROKER_PORT: "{{ .Values.config.celery.brokerPort }}"
  FP_CELERY_BROKER_DB: "{{ .Values.config.celery.brokerDb }}"
  FP_CELERY_RESULTS_TTL_DAYS: "{{ .Values.config.celery.resultsTtlDays }}"
  FP_CELERY_TASK_TLIMIT_HARD: "{{ .Values.config.celery.taskTlimitHard }}"
  FP_CELERY_TASK_TLIMIT_SOFT: "{{ .Values.config.celery.taskTlimitSoft }}"
  FP_RESULTS_TEMP_TTL_HOURS: "{{ .Values.config.resultCache.resultsTempTtlHours }}"
  FP_JOB_STATUS_TTL_DAYS: "{{ .Values.config.celery.jobStatusTtlDays }}"
  FP_SYNC_EXECUTION_TIMEOUT_SECONDS: "{{ .Values.config.syncExecutionTimeoutSeconds }}"
  FP_LOG_LEVEL: "{{ .Values.config.logLevel }}"

  NP_JAVA_LIB_DIR: "{{ .Values.config.javaLibDir }}"
  NP_LOG_LEVEL: "{{ .Values.config.logLevel }}"
  NP_JAVA_MAX_HEAP_SIZE: "{{ .Values.config.javaMaxHeapSize }}"
  NP_JAVA_INITIAL_HEAP_SIZE: "{{ .Values.config.javaInitialHeapSize }}"