apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noise-modelling-api.fullname" . }}-api
  labels:
    {{- include "noise-modelling-api.selectorLabels" . | nindent 4 }}
    component: api
    {{- with .Values.podLabels.api }}
    {{- toYaml . | nindent 8 }}
    {{- end }}

spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      {{- include "noise-modelling-api.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "noise-modelling-api.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector.api }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.api }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1 --log-level info
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "noise-modelling-api.fullname" . }}
          env:
            - name: CELERY_BROKER_PASSWORD
          {{- if .Values.config.celery.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.celery.existingSecret }}
                  key: {{ .Values.config.celery.existingSecret }}
          {{- else }}
              value: ""
          {{- end }}
            - name: RESULT_CACHE_PASSWORD
          {{- if .Values.config.celery.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.resultCache.existingSecret }}
                  key: {{ .Values.config.resultCache.existingSecret }}
          {{- else }}
              value: ""
          {{- end }}
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
