{{- if .Values.autoscaling.api.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "noise-modelling-api.fullname" . }}-api
  labels:
    {{- include "noise-modelling-api.labels" . | nindent 4 }}
  annotations:
    description: "HPA for the API component handling HTTP requests"
    recommended-max-replicas: "{{ .Values.autoscaling.api.maxReplicas }}"
    metric-provider: "kubernetes/metrics-server"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "noise-modelling-api.fullname" . }}-api
  minReplicas: {{ .Values.autoscaling.api.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.api.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.api.hpa.targetCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.api.hpa.targetMemoryUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
{{- end }}